# Python CircleCI 2.0 configuration file
#
# Check httpscircleci.comdocs2.0language-python for more details
#
version 2
jobs
build
docker
# Use the same Docker base as the project
- image python3.7.3-stretch

working_directory ~repo

steps
- checkout

# Download and cache dependencies
- restore_cache
keys
- v1-dependencies-{{ checksum requirements.txt }}
# fallback to using the latest cache if no exact match is found
- v1-dependencies-

- run
name install dependencies
command 
python3 -m venv venv
. venvbinactivate
make install
# Install hadolint
wget -O binhadolint httpsgithub.comhadolinthadolintreleasesdownloadv1.16.3hadolint-Linux-x86_64 &&
chmod +x binhadolint
- save_cache
paths
- .venv
key v1-dependencies-{{ checksum requirements.txt }}

# run lint!
- run
name run lint
command 
. venvbinactivate
make lint 